services:
  backend:
    image: ${BACKEND_IMAGE:-ad_sim-backend:latest}
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: ad_sim_backend
    ports:
      - '5001:5001'
    environment:
      - PORT=5001
    volumes:
      - ./backend/simulation_output:/app/backend/simulation_output

  frontend:
    image: ${FRONTEND_IMAGE:-ad_sim-frontend:latest}
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: ad_sim_frontend
    ports:
      - '3000:80'
